### ISSUE TITLE
pipeline.yaml file is not uploaded in databricks. 

### ISSUE THREAD

**Issue by Mehroz01** [mlflow/mlp-regression-template#49]
My cluster run time environment is 9.1. whenever I am cloning the repo https://github.com/mlflow/mlp-regression-template. 
It's just cloned folders. When I run a code I got an error pipeline.YAML not found, Can anyone suggest to me what will be the issue.
![image](https://user-images.githubusercontent.com/40281788/180030346-6ed9ff1f-2396-41ed-84c0-8f0549cd253b.png)

**Comment by paprocki-r** [comment]
I am getting the same problem - cloned repository is empty besides the notebook. When I download the repo and try to import a zip to databricks' workspace I am getting this error: 
![image](https://user-images.githubusercontent.com/3410289/181232833-eb06e2f6-e159-4466-af5a-57c78df89903.png)

It is probably related to the fact that:
![image](https://user-images.githubusercontent.com/3410289/181233023-dd1b3cc8-528d-4a71-af24-09570861a832.png)
(this error I'm getting when I try to clone repo of https://github.com/mlflow/mlflow-example )

Now, the solution is to go to Databricks->Settings (lower bottom gear icon) -> Admin Console -> Workspace Settings and then choose appropriate option:
![image](https://user-images.githubusercontent.com/3410289/181233857-edb106d5-1e77-48a4-accf-f84d616da39d.png)
Then try to clone the repo again - it should work

**Comment by jeannefukumaru** [comment]
Hi, Files in Repos needs to be enabled in order to view repo artifacts that are not notebooks. As @paprocki-r mentioned, you can go to Databricks->Settings (lower bottom gear icon) -> Admin Console -> Workspace Settings and enable the Files in Repos feature. Hope this helps.

**Comment by Mehroz01** [comment]
Hi @jeannefukumaru I have resolved issues in the same way that you explained above, Sorry for the Response late.
Thank you all, everything is working fine and I have trained multiple models using mlflow. It's an amazing tool.
